### ISSUE TITLE
导航组件pub.dev搜不到，是还没有上传吗

### ISSUE THREAD

**Issue by chendengyuanxm** [fluttify-project/amap_navi_fluttify#1]

**Comment by yohom** [comment]
导航组件，暂时没有开发计划。建议使用跳转到地图app的方式来进行导航。

**Comment by chendengyuanxm** [comment]
> 导航组件，暂时没有开发计划。建议使用跳转到地图app的方式来进行导航。

我看navi上已经有代码了，问下目前master直接把代码下载下来是否可以支持，大概计划什么时候会进行navi的开发。谢谢！

**Comment by yohom** [comment]
导航sdk由于包含了地图sdk，生成出来的代码太多，导致android端编译失败（方法体超过了jvm限制）。目前地图插件(0.5.3起)有跳转到高德app导航的方法，`AmapService::navigateDrive`你可以参考下。
